### ISSUE TITLE
There may be an error.

### ISSUE THREAD

**Issue by Haoyu-Xie** [Linwei-Tao/NCI-Gadi-tutorial#1]
Thanks for your kind guiding.

But I try to run the shell, returned some Error: 'Error: You are not a member of project $PROJECT. You must be a member of a project to submit a job under that project.'
Because if '#PBS -P $PROJECT', the project name will be '$PROJECT', rather than your project name.
PBS may can not read the global variable '$PROJECT'.
Here, it should be your real project name, e.g. '#PBS -P uo40'.

**Comment by Linwei94** [comment]
Thank you for reminding. The HPC system has updated recently. I will correct it.
